# syntax=docker/dockerfile:1

# Stage 1: Build hmdm-server + location plugin from source.
# Requires submodules to be initialised before running docker build:
#   git submodule update --init --recursive
FROM maven:3.8-openjdk-11 AS builder

# Copy hmdm-server source from the checked-out submodule
COPY hmdm-server/ /build/hmdm-server/

# Copy location plugin into plugins/locationmap/ so that:
#  - ../pom.xml (= plugins/pom.xml) resolves as the parent
#  - the iterator-maven-plugin in server/pom.xml picks up its
#    src/main/webapp resources and bundles them into the WAR
COPY hmdm-server-plugin_location-map/ /build/hmdm-server/plugins/locationmap/

# Provide a build.properties so maven-resources-plugin can filter conf/.
# Values are compile-time only; runtime config is generated by
# docker-entrypoint.sh from environment variables.
RUN cp /build/hmdm-server/server/build.properties.example \
       /build/hmdm-server/server/build.properties

# Build server + built-in plugins; installs com.hmdm.plugin:platform
# into the local Maven repo (required by locationmap).
WORKDIR /build/hmdm-server
RUN mvn install -DskipTests -q

# Build the location plugin JAR
WORKDIR /build/hmdm-server/plugins/locationmap
RUN mvn package -DskipTests -q

# Collect artifacts at fixed paths for the final stage
RUN mkdir -p /artifacts/plugins \
    && cp /build/hmdm-server/server/target/launcher.war /artifacts/hmdm.war \
    && cp /build/hmdm-server/plugins/locationmap/target/locationmap-*.jar \
           /artifacts/plugins/locationmap.jar


# Stage 2: Runtime
FROM tomcat:9-jdk11-temurin-jammy

RUN apt-get update \
    && apt-get upgrade -y
RUN apt-get install -y \
		aapt \
		wget \
		sed \
        postgresql-client \
	&& rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/tomcat/conf/Catalina/localhost
RUN mkdir -p /usr/local/tomcat/ssl

# Set to 1 to force updating the config files
# If not set, they will be created only if there's no files
#ENV FORCE_RECONFIGURE=true
ENV FORCE_RECONFIGURE=

# Available values: en, ru (en by default)
ENV INSTALL_LANGUAGE=en

#ENV ADMIN_EMAIL=

# Different for open source and premium versions!
ENV SHARED_SECRET=changeme-C3z9vi54

ENV HMDM_VARIANT=os
ENV DOWNLOAD_CREDENTIALS=
# HMDM_URL is used only when falling back to a downloaded WAR (pre-built image);
# left empty here because the source-built WAR is baked into the image.
ENV HMDM_URL=
ENV CLIENT_VERSION=6.34

ENV SQL_HOST=localhost
ENV SQL_PORT=5432
ENV SQL_BASE=hmdm
ENV SQL_USER=hmdm
ENV SQL_PASS=Ch@nGeMe

ENV PROTOCOL=https
#ENV BASE_DOMAIN=your-domain.com

# Set this parameter to your local IP address
# if your server is behind the NAT
#ENV LOCAL_IP=172.31.91.82

# Comment it to use custom certificates
ENV HTTPS_LETSENCRYPT=true
# Mount the custom certificate path if custom certificates must be used
# ENV_HTTPS_CERT_PATH is the path to certificates and keys inside the container
#ENV HTTPS_CERT_PATH=/cert
ENV HTTPS_CERT=cert.pem
ENV HTTPS_FULLCHAIN=fullchain.pem
ENV HTTPS_PRIVKEY=privkey.pem

EXPOSE 8080
EXPOSE 8443
EXPOSE 31000

# Copy built WAR and location plugin JAR from builder stage
COPY --from=builder /artifacts/ /opt/hmdm/artifacts/

COPY docker-entrypoint.sh /
COPY update-web-app-docker.sh /opt/hmdm/
COPY tomcat_conf/server.xml /usr/local/tomcat/conf/server.xml
ADD templates /opt/hmdm/templates/

ENTRYPOINT ["/docker-entrypoint.sh"]
